### ISSUE TITLE
Codestyle: Add continuation line policy

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/documentation#27]
_From @fneu on July 15, 2016 21:2_

Basically we are already enforcing a style, where multiple-line lists, dicts, tuples, function definitions, function calls, and any such structures either:

- stay in one line
- span multiple lines that list one parameter/ item each

Since this is not covered by PEP8 we should add a section to our [codestyle](https://github.com/coala-analyzer/coala/blob/master/docs/Getting_Involved/Codestyle.rst)

_Copied from original issue: coala-analyzer/coala#2454_

**Comment by Adrianzatreanu** [comment]
_From @gitmate-bot on July 15, 2016 21:2_

Thanks for reporting this issue!

Your aid is required, fellow coalaian. Help us triage and solving this issue!

CC @sils1297, @AbdealiJK

**Comment by petrjoachim** [comment]
I'd like to work on this one :trollface:
