### ISSUE TITLE
docs: Add information about long issue discussions handling

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/documentation#45]
_From @Uran198 on April 13, 2016 16:19_

From the discussion in #1875.
It should be documented that after the long discussion, should be created new issue with clearly defined task.

_Copied from original issue: coala-analyzer/coala#2010_

**Comment by Adrianzatreanu** [comment]
_From @gitmate-bot on April 13, 2016 16:19_

Thanks for reporting this issue!

Your aid is required, fellow coalaian. Help us triage and solving this issue!

CC @sils1297, @AbdealiJK

**Comment by Adrianzatreanu** [comment]
_From @AbdealiJK on April 25, 2016 9:3_

Where should this be added ? which file ?

**Comment by Adrianzatreanu** [comment]
_From @Uran198 on April 25, 2016 16:2_

I think either in the wiki, at Maintainer's corner, or in the docs at getting involved.

**Comment by Adrianzatreanu** [comment]
_From @sils1297 on April 25, 2016 16:3_

Good idea.

**Comment by ladaradon** [comment]
I`d like to this one
