### ISSUE TITLE
Mention `bear_dirs` in `icollect_bears` is a glob in documentation

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/documentation#52]
_From @hypothesist on March 5, 2016 7:29_

_Copied from original issue: coala-analyzer/coala#1807_

**Comment by Adrianzatreanu** [comment]
_From @hypothesist on March 5, 2016 7:58_

Also change the variable name from `bear_dirs` to `bear_dir_glob` as it is more appropriate. (Also make the corresponding changes in the docs :) )

**Comment by msgre** [comment]
Should I try this?
