### ISSUE TITLE
Writing_Good_Commits: Be consistent with title underlinings

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/documentation#65]
sometimes
```
Hello
\~~~~~
```
```
World
-----
```
are both used. We should be consistent.

(Ignore the backslash above, GitHub has a rendering fault otherwise^^)

**Comment by Makman2** [comment]
Would vote for plain dashes: `-----`

**Comment by Adrianzatreanu** [comment]
@Makman2 those are levels of titles.
biggest title uses ======
a subtitle of that page uses ------
and an even deeper subtitle that belongs to a ---- is a ~~~~~~

**Comment by Makman2** [comment]
ahhhhhh I thought `----` means the same `~~~~~`
