### ISSUE TITLE
Writing_Good_Commits: Remove "the" in enumeration

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/documentation#67]
Inside lines 26-28:
> - ~~the~~ shortlog
- ~~the~~ commit body
- ~~the~~ issue reference

as without "the" readability is improved.

**Comment by tamj0rd2** [comment]
I'd like to get assigned :)

**Comment by Makman2** [comment]
@tamj0rd2 invited you to our org :) after you accepted I'll assign you officially, but you can already start working :+1:

if you need help, be sure to drop by at out gitter channel: https://gitter.im/coala-analyzer/coala
:D

**Comment by Adrianzatreanu** [comment]
assigned!
