### ISSUE TITLE
Get help with git: Use our own git guide?

### ISSUE THREAD

**Issue by sims1253** [coala-analyzer/documentation#74]
http://coala-docs.readthedocs.io/en/latest/Developers/Newcomers_Guide.html#optional-get-help-with-git

Why not use the git guides lasse wrote? They teach you about rebase afaik.

**Comment by Adrianzatreanu** [comment]
cuz theres already http://coala-docs.readthedocs.io/en/latest/Developers/Git_Basics.html which i wrote and other people contributed to, and lasse decided to drop the hitchhiker one

**Comment by sims1253** [comment]
well ok then :)
