### ISSUE TITLE
Fix typo: docs/Git_hooks: standars -> standards

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/documentation#75]
_From @hypothesist on July 21, 2016 12:22_

_Copied from original issue: coala-analyzer/coala#2473_

**Comment by Adrianzatreanu** [comment]
_From @sils1297 on August 20, 2016 20:38_

ahm @hypothesist why is this not in the documentation repository?

**Comment by Adrianzatreanu** [comment]
_From @sils1297 on August 20, 2016 21:16_

CC @Adrianzatreanu

**Comment by OndraSky** [comment]
On it

**Comment by OndraSky** [comment]
There is no _ standars_ word in the repo.

**Comment by sils1297** [comment]
THanks, closing. Sorry for the inconvenience :/
